<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/28 0028
 * Time: 20:25
 */
namespace app\models;
use yii\db\ActiveRecord;
class Test  extends ActiveRecord{//表示活动记录-存在于一个命名空间
  /*public function rules()//rules()函数对数据进行验证，返回一个数组
  {
      return [
         ['id','integer'],//验证id是否是整型数据
         ['title','string','length'=>[0,6]]//验证器看文档
      ]; // TODO: Change the autogenerated stub
  }*/
}
?>